# Mileston Inference

## Library Import

In [1]:
import pandas as pd
import joblib

We will only use two libraries :
- pandas will allow use to create and manipulate dataframe
- joblib will allow use to load the model we have made

## Model Loading

In [2]:
def array_to_dataframe(X, columns):
    """Convert numpy array back to DataFrame for ColumnTransformer compatibility."""
    return pd.DataFrame(X, columns=columns)
with open('model_best.pkl', 'rb') as file_5:
  model_best = joblib.load(file_5)

We will load the model we have developed

## Inference Data & Result

I will create different inference data to test the model accuracy. I will give suggestion based on the results

### 1. Fresh graduate

In [3]:
freshgrad = {
    'Age': [22, 23, 22], 
    'DailyRate': [1000,400,400], # One candidate has referrals while others don't yet
    'DistanceFromHome': [10,20,5], 
    'MonthlyIncome': [2000, 2000, 2000], #Assuming same salary
    'TotalWorkingYears': [0,0,0], 
    'TrainingTimesLastYear': [0,0,0], 
    'YearsAtCompany': [0,0,0], 
    'BusinessTravel':['Travel_Frequently', 'Travel_Rarely', 'Non-Travel'], 
    'Department': ['Sales', 'Human Resources', 'Research & Development'], # Adjusted based on the business travel
    'OverTime': ['Yes', 'Yes', 'Yes'], #All newly hires usually does overtime to leave a good impression for the company 
    'EnvironmentSatisfaction': [3,2,2], 
    'JobSatisfaction': [2,2,2], 
    'StockOptionLevel': [0,0,0], 
    'WorkLifeBalance': [1,1,1]
}
freshgrad = pd.DataFrame(freshgrad)
freshgrad

,Age,DailyRate,DistanceFromHome,MonthlyIncome,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,BusinessTravel,Department,OverTime,EnvironmentSatisfaction,JobSatisfaction,StockOptionLevel,WorkLifeBalance
0,22,1000,10,2000,0,0,0,Travel_Frequently,Sales,Yes,3,2,0,1
1,23,400,20,2000,0,0,0,Travel_Rarely,Human Resources,Yes,2,2,0,1
2,22,400,5,2000,0,0,0,Non-Travel,Research & Development,Yes,2,2,0,1

In [4]:
model_best

Pipeline(steps=[('transformer',
                 ColumnTransformer(transformers=[('num_scaler',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['Age', 'DailyRate',
                                                   'DistanceFromHome',
                                                   'MonthlyIncome',
                                                   'TrainingTimesLastYear']),
                                                 ('num_minmax',
                                                  Pipeline(steps=[('minmax',
                                                                   MinMaxScaler())]),
                                                  ['TotalWorkingYears',
                                                   'YearsAtCompany']),
                                                 ('cat_onehot',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEnc...
                                                          'cat_onehot__Department_Research '
                                                          '& Development',
                                                          'cat_onehot__Department_Sales',
                                                          'cat_onehot__OverTime_Yes',
                                                          'cat_ordinal__BusinessTravel',
                                                          'passthrough__EnvironmentSatisfaction',
                                                          'passthrough__JobSatisfaction',
                                                          'passthrough__StockOptionLevel',
                                                          'passthrough__WorkLifeBalance']})),
                ('classifier',
                 SVC(C=10, gamma=1, kernel='linear', probability=True,
                     random_state=2))])

In [5]:
y_pred_inf = model_best.predict(freshgrad)
print(y_pred_inf)

[1 1 1]

According to this machine, fresh graduate that hasn't worked will have higher chance of attrition. Attrition is usually caused by:
1.  Inadequate compensation/benefit
2.  Work/life imbalance
3.  Unrealistic Expectation
4.  Ineffective management practive
5.  Misallignment with workplace culture
6.  Lack of career advancement opportunities

For fresh graduate, these might be the cause for them to get attrited. So company must do the opposite to keep these type of people.

https://www.shrm.org/topics-tools/news/employee-relations/attrition-definition-types-causes-mitigation-tips

### 2. Experienced Hire

In [6]:
experienced = {
    'Age': [30, 33, 32], 
    'DailyRate': [1000,100,200], # One candidate has referrals while others don't yet just like the data above
    'DistanceFromHome': [10,20,5], 
    'MonthlyIncome': [5000, 5000, 5000], #Assuming same salary just like above data
    'TotalWorkingYears': [10,10,10], 
    'TrainingTimesLastYear': [0,0,0], 
    'YearsAtCompany': [0,0,0], 
    'BusinessTravel':['Travel_Frequently', 'Travel_Rarely', 'Non-Travel'], 
    'Department': ['Sales', 'Human Resources', 'Research & Development'], # Adjusted based on the business travel
    'OverTime': ['Yes', 'Yes', 'Yes'], #All newly hires usually does overtime to leave a good impression for the company 
    'EnvironmentSatisfaction': [3,2,2], 
    'JobSatisfaction': [2,2,2], 
    'StockOptionLevel': [1,2,1], # Experienced hire (mostly managers) will always given the privilege of owning a company's stock
    'WorkLifeBalance': [2,3,1]
}

experienced = pd.DataFrame(experienced)
experienced

,Age,DailyRate,DistanceFromHome,MonthlyIncome,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,BusinessTravel,Department,OverTime,EnvironmentSatisfaction,JobSatisfaction,StockOptionLevel,WorkLifeBalance
0,30,1000,10,5000,10,0,0,Travel_Frequently,Sales,Yes,3,2,1,2
1,33,100,20,5000,10,0,0,Travel_Rarely,Human Resources,Yes,2,2,2,3
2,32,200,5,5000,10,0,0,Non-Travel,Research & Development,Yes,2,2,1,1

In [7]:
y_pred_exp = model_best.predict(experienced)
print(y_pred_exp)

[1 1 1]

Just like the results from above, this model was not made for people outside of the company.

### 3. Happy workers in the company

In [8]:
workers = {
    'Age': [30, 33, 32], 
    'DailyRate': [17000,1000,2000],
    'DistanceFromHome': [10,20,5], 
    'MonthlyIncome': [10000, 9000, 8500], 
    'TotalWorkingYears': [5,6,7], 
    'TrainingTimesLastYear': [2,2,3], 
    'YearsAtCompany': [5,6,7], 
    'BusinessTravel':['Travel_Frequently', 'Travel_Rarely', 'Non-Travel'], 
    'Department': ['Sales', 'Human Resources', 'Research & Development'], 
    'OverTime': ['No', 'No', 'No'], #Assumes no overtime
    'EnvironmentSatisfaction': [4,4,4], 
    'JobSatisfaction': [4,4,4], 
    'StockOptionLevel': [2,2,2], 
    'WorkLifeBalance': [3,3,3]
}
workers= pd.DataFrame(workers)
workers

,Age,DailyRate,DistanceFromHome,MonthlyIncome,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,BusinessTravel,Department,OverTime,EnvironmentSatisfaction,JobSatisfaction,StockOptionLevel,WorkLifeBalance
0,30,17000,10,10000,5,2,5,Travel_Frequently,Sales,No,4,4,2,3
1,33,1000,20,9000,6,2,6,Travel_Rarely,Human Resources,No,4,4,2,3
2,32,2000,5,8500,7,3,7,Non-Travel,Research & Development,No,4,4,2,3

In [9]:
y_pred_wrk = model_best.predict(workers)
print(y_pred_wrk)

[0 0 0]

These are the data for the happy workers in the company. This results are expected

Just in case, here are signs of high attrition risk:
- Decreased productivity
- Reduced participation
- Increased abseentism

Companies need to watch out for these signs

https://www.hibob.com/blog/attrition-indicator/

### 4. Unhappy workers in the company

In [10]:
unhappy = {
    'Age': [30, 33, 32], 
    'DailyRate': [100,100,100],
    'DistanceFromHome': [10,20,5], 
    'MonthlyIncome': [10000, 9000, 8500], 
    'TotalWorkingYears': [5,6,7], 
    'TrainingTimesLastYear': [0,0,0], 
    'YearsAtCompany': [5,6,7], 
    'BusinessTravel':['Travel_Frequently', 'Travel_Rarely', 'Non-Travel'], 
    'Department': ['Sales', 'Human Resources', 'Research & Development'], 
    'OverTime': ['Yes', 'Yes', 'Yes'], 
    'EnvironmentSatisfaction': [1,1,1], 
    'JobSatisfaction': [1,1,1], 
    'StockOptionLevel': [1,1,1], 
    'WorkLifeBalance': [1,1,1]
}
unhappy= pd.DataFrame(unhappy)
y_pred_unh = model_best.predict(unhappy)
print(y_pred_unh)

[1 1 1]

The results are to be expected, because from the data above we can tell that the workers are demotivated which may cause their performance to decline too.

### 5. People in retirement age

In [11]:
old = {
    'Age': [70, 73, 72], 
    'DailyRate': [50,50,100],
    'DistanceFromHome': [10,20,5], 
    'MonthlyIncome': [10000, 9000, 8500], 
    'TotalWorkingYears': [45,46,47], 
    'TrainingTimesLastYear': [0,0,0], 
    'YearsAtCompany': [45,46,47], 
    'BusinessTravel':['Travel_Frequently', 'Travel_Rarely', 'Non-Travel'], 
    'Department': ['Sales', 'Human Resources', 'Research & Development'], 
    'OverTime': ['No', 'No', 'No'], #Old people cannot have overtime
    'EnvironmentSatisfaction': [2,2,2], 
    'JobSatisfaction': [2,2,2], 
    'StockOptionLevel': [1,1,1], 
    'WorkLifeBalance': [3,3,3]
}
old= pd.DataFrame(old)
y_pred_old = model_best.predict(old)
print(y_pred_old)

[0 0 0]

These are not the result we want because these are the age of retirement. This is an example of false negative in our model

## Insight
- From the freshgraduate data, we can see that attrition may happen because the model was made for employees within the company. Employee outside will have higher chance of being marked as attrited because this model was not made to analyze potential candidates
- This model still has the tendency to have false negative prediction from what we see in the data for people in retirement age, which is what we want to minimize as much as possible.